# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculo_Media.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtCore, QtGui,QtWidgets
from PyQt5.QtWidgets import QMessageBox


class Ui_Janela(object):
    def setupUi(self, Janela):
        Janela.setObjectName("Janela")
        Janela.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(Janela)
        self.centralwidget.setObjectName("centralwidget")

        self.botao1 = QtWidgets.QPushButton(self.centralwidget)
        self.botao1.setGeometry(QtCore.QRect(50, 450, 161, 81))
        self.botao1.setObjectName("botao1")
        self.botao2 = QtWidgets.QPushButton(self.centralwidget)
        self.botao2.setGeometry(QtCore.QRect(390, 450, 151, 81))
        self.botao2.setObjectName("botao2")

        self.nota1 = QtWidgets.QLineEdit(self.centralwidget)
        self.nota1.setGeometry(QtCore.QRect(140, 120, 113, 20))
        self.nota1.setObjectName("nota1")

        self.nota2 = QtWidgets.QLineEdit(self.centralwidget)
        self.nota2.setGeometry(QtCore.QRect(140, 160, 113, 20))
        self.nota2.setObjectName("nota2")

        self.nota3 = QtWidgets.QLineEdit(self.centralwidget)
        self.nota3.setGeometry(QtCore.QRect(140, 210, 113, 20))
        self.nota3.setObjectName("nota3")

        self.nota4 = QtWidgets.QLineEdit(self.centralwidget)
        self.nota4.setGeometry(QtCore.QRect(140, 250, 113, 20))
        self.nota4.setObjectName("nota4")

        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(80, 120, 51, 21))
        self.label1.setObjectName("label1")

        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(80, 160, 51, 21))
        self.label2.setObjectName("label2")

        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(80, 210, 51, 21))
        self.label3.setObjectName("label3")

        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(80, 250, 51, 21))
        self.label4.setObjectName("label4")
     

        Janela.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Janela)
        self.statusbar.setObjectName("statusbar")
        Janela.setStatusBar(self.statusbar)

        self.retranslateUi(Janela)
        QtCore.QMetaObject.connectSlotsByName(Janela)

        #Ações
        self.botao1.clicked.connect(self.calculoMedia)
        self.botao1.clicked.connect(self.enviarMensagem)

    def retranslateUi(self, Janela):
        _translate = QtCore.QCoreApplication.translate
        Janela.setWindowTitle(_translate("Janela", "Primeira Janela"))
        self.botao1.setText(_translate("Janela", "Média"))
        self.botao2.setText(_translate("Janela", "Cancelar"))
        self.label1.setText(_translate("Janela", "Nota 01"))
        self.label2.setText(_translate("Janela", "Nota 02"))
        self.label3.setText(_translate("Janela", "Nota 03"))
        self.label4.setText(_translate("Janela", "Nota 04"))

    def calculoMedia(self):
        
        nota1 = float(self.nota1.text())
        nota2 = float(self.nota2.text())
        nota3 = float(self.nota3.text())
        nota4 = float(self.nota4.text())
        
        media = (nota1+nota2+nota3+nota4)/4

    def enviarMensagem (self):
        media = QtWidgets.QMessageBox()
        media.setText(Principal,"Media: "+str(media))
        
if __name__ == "__main__":
    app = QtWidgets.QApplication(sys.argv)
    Principal = QtWidgets.QMainWindow()
    ui=Ui_Janela()
    ui.setupUi(Principal)
    Principal.show()
    sys.exit(app.exec_())